# Generated by Django 2.2.7 on 2019-11-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('game_has_started', models.BooleanField(default=False)),
                ('game_id', models.IntegerField(default=None, null=True)),
                ('board', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_in_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lobby.Room')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('room', 'name')},
            },
        ),
    ]
